version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  python:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    working_dir: /app/dbt/telegram_dbt
    volumes:
      - .:/app
      - /c/Users/user/.dbt:/root/.dbt
    ports:
      - "8080:8080" 
    command: tail -f /dev/null 
volumes:
  pgdata:
